import { StyleSheet } from 'react-native';

export const colors = {
  background: '#fdfd96', 
  borderColor: '#ff69b4', 
  buttonBackground: '#ff69b4', 
  buttonDanger: '#ff4500', 
  buttonSecondary: '#ffdf00', 
  buttonText: '#fff', 
  title: 'black', 
};

export const styles = StyleSheet.create({
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
    justifyContent: 'center',
    marginVertical: 2,
    minWidth: 80,
    padding: 10,
  },
  actionButtonContainer: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  actionButtonText: {
    color: '#333',
  },
  bordaExternaImagemFornecedor: {
    borderWidth: 2, 
    borderColor: 'black', 
    borderRadius: 30, 
    padding: 2, 
  },

  bordaInternaImagemFornecedor: {
    borderWidth: 2, 
    borderColor: '#ff69b4', 
    borderRadius: 26, 
    overflow: 'hidden', 
  },
  botao: {
    alignSelf: 'center',
    backgroundColor: colors.buttonBackground,
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 2,
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
    width: '80%',
  },
  botaoAlterar: {
    alignSelf: 'flex-end',
    backgroundColor: colors.buttonBackground,
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 2,
    marginVertical: 5,
    padding: 10,
  },
  botaoExcluir: {
    alignSelf: 'flex-end',
    backgroundColor: colors.buttonDanger,
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 2,
    marginVertical: 5,
    padding: 10,
  },
  botaoSecundario: {
    alignItems: 'center',
    backgroundColor: colors.buttonSecondary,
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 2,
    marginVertical: 10,
    padding: 10,
  },
  botaoTexto: {
    color: '#000',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonGroup: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  container: {
    alignItems: 'center',
    backgroundColor: colors.background,
    flex: 1,
    justifyContent: 'center',
  },
  containerFornecedor: {
    backgroundColor: colors.background,
    padding: 20,
  },
  fornecedorImagemBorder: {
    backgroundColor: '#ff69b4', 
    borderRadius: 28, 
    padding: 2, 
  },
  fornecedorImagemWrapper: {
    backgroundColor: '#000', 
    borderRadius: 30, 
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2, 
  },
  imagem: {
    borderColor: '#ff69b4',
    borderRadius: 50,
    borderWidth: 3,
    height: 100,
    width: 100,
  },
  imagemContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  imagemEscolhida: {
    alignSelf: 'center',
    borderColor: 'black',
    borderRadius: 75,
    borderWidth: 3,
    height: 150,
    marginBottom: 20,
    marginTop: 20,
    overflow: 'hidden',
    width: 150,
  },
  imagemEscolhidaInner: {
    borderColor: colors.borderColor,
    borderRadius: 75,
    borderWidth: 4,
    height: '100%',
    width: '100%',
  },
  imagemFornecedor: {
    width: 50, 
    height: 50, 
    borderRadius: 25, 
    resizeMode: 'cover', 
  },
  imagemFornecedorContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10, 
    marginVertical: 5,
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  input: {
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderColor: colors.buttonBackground,
    borderRadius: 10,
    borderWidth: 1,
    height: 40,
    marginVertical: 10,
    padding: 10,
    width: '80%',
  },
  item: {
    alignItems: 'center',
    borderBottomColor: colors.borderColor,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    paddingRight: 20,
  },
  itemContainer: {
    backgroundColor: '#fff',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  itemTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#000',
    borderRadius: 52,
    borderWidth: 2,
    justifyContent: 'center',
    padding: 2,
  },
  nome: {
    color: colors.title,
    fontWeight: 'bold',
  },
  sectionHeader: {
    backgroundColor: colors.buttonBackground,
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    padding: 10,
  },
  texto: {
    color: '#333',
  },
  titulo: {
    color: colors.title,
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 20,
    textAlign: 'center',
  },
});
